Document: qtquickcontrols
Title: Debian qtquickcontrols Manual
Author: <insert document author here>
Abstract: This manual describes what qtquickcontrols is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qtquickcontrols/qtquickcontrols.sgml.gz

Format: postscript
Files: /usr/share/doc/qtquickcontrols/qtquickcontrols.ps.gz

Format: text
Files: /usr/share/doc/qtquickcontrols/qtquickcontrols.text.gz

Format: HTML
Index: /usr/share/doc/qtquickcontrols/html/index.html
Files: /usr/share/doc/qtquickcontrols/html/*.html
